<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Vite;
use Symfony\Component\HttpFoundation\Response;

class SecurityHeaders
{
    /**
     * Handle an incoming request and add security headers to the response.
     */
    public function handle(Request $request, Closure $next): Response
    {
        // Enable CSP nonce for first-party script/style tags generated by Vite
        Vite::useCspNonce();

        $response = $next($request);

        // Prevent MIME type sniffing
        $response->headers->set('X-Content-Type-Options', 'nosniff');

        // Prevent clickjacking attacks - SAMEORIGIN allows framing from same origin
        $response->headers->set('X-Frame-Options', 'SAMEORIGIN');

        // Enable XSS protection (legacy header, CSP is preferred but included for older browsers)
        $response->headers->set('X-XSS-Protection', '1; mode=block');

        // Refuse to be framed by other origins at the CSP level as well
        // (modern replacement for X-Frame-Options)
        $cspFrameAncestors = "frame-ancestors 'self'";

        // Control referrer information sent with requests
        $response->headers->set('Referrer-Policy', 'strict-origin-when-cross-origin');

        // Content Security Policy using Vite nonce for scripts and styles
        // In local/testing, relax policy to support Vite dev server, HMR (ws), and Alpine.
        $nonce = Vite::cspNonce();
        $env = config('app.env');
        $isLocalOrTesting = in_array($env, ['local', 'development', 'testing'], true);

        // Default policy (production / staging): include CSP nonce and avoid inline execution
        $scriptSrc = ["'self'", "'nonce-{$nonce}'"];
        $styleSrc = ["'self'", "'nonce-{$nonce}'"];
        $connectSrc = ["'self'"];
        $imgSrc = ["'self'", 'data:'];
        $fontSrc = ["'self'", 'data:', 'https://fonts.bunny.net', 'https://fonts.gstatic.com'];

        if ($isLocalOrTesting) {
            // Local / testing: remove nonce requirements so inline scripts/styles work
            // and enable dev hosts + relaxed policies for DX.
            $scriptSrc = [
                "'self'",
                "'unsafe-inline'",
                "'unsafe-eval'",
                'http://127.0.0.1:5173',
                'https://newsblog.test:5173',
                'https://cdn.jsdelivr.net',
                'https://unpkg.com',
                'https://cdnjs.cloudflare.com',
            ];
            $styleSrc = [
                "'self'",
                "'unsafe-inline'",
                'http://127.0.0.1:5173',
                'https://newsblog.test:5173',
                'https://fonts.bunny.net',
            ];
            $connectSrc = array_merge($connectSrc, [
                'http://127.0.0.1:5173',
                'ws://127.0.0.1:5173',
                'https://newsblog.test:5173',
                'wss://newsblog.test:5173',
            ]);
        } else {
            // Alpine may require 'unsafe-eval' for expression parsing
            $scriptSrc[] = "'unsafe-eval'";
        }

        $csp = implode('; ', [
            "default-src 'self'",
            "base-uri 'self'",
            $cspFrameAncestors,
            'img-src '.implode(' ', $imgSrc),
            'font-src '.implode(' ', $fontSrc),
            "object-src 'none'",
            'connect-src '.implode(' ', $connectSrc),
            'script-src '.implode(' ', array_unique($scriptSrc)),
            'style-src '.implode(' ', array_unique($styleSrc)),
            "frame-src 'self'",
            "form-action 'self'",
        ]);
        $response->headers->set(
            'Content-Security-Policy',
            $csp
        );

        // Restrict browser features
        $response->headers->set('Permissions-Policy', 'geolocation=(), microphone=(), camera=(), payment=(), usb=(), bluetooth=()');

        // Force HTTPS in production
        if (config('app.env') === 'production') {
            $response->headers->set('Strict-Transport-Security', 'max-age=31536000; includeSubDomains');
        }

        return $response;
    }
}
