<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Vite;
use Symfony\Component\HttpFoundation\Response;

class SecurityHeaders
{
    /**
     * Handle an incoming request and add security headers to the response.
     */
    public function handle(Request $request, Closure $next): Response
    {
        // Enable CSP nonce for first-party script/style tags generated by Vite
        Vite::useCspNonce();

        $response = $next($request);

        // Prevent MIME type sniffing
        $response->headers->set('X-Content-Type-Options', 'nosniff');

        // Prevent clickjacking attacks - SAMEORIGIN allows framing from same origin
        $response->headers->set('X-Frame-Options', 'SAMEORIGIN');

        // Refuse to be framed by other origins at the CSP level as well
        // (modern replacement for X-Frame-Options)
        $cspFrameAncestors = "frame-ancestors 'self'";

        // Control referrer information sent with requests
        $response->headers->set('Referrer-Policy', 'strict-origin-when-cross-origin');

        // Content Security Policy using Vite nonce for scripts and styles
        // Allow self for all; disallow inline except for nonce-bound assets
        $nonce = Vite::cspNonce();
        $csp = implode('; ', [
            "default-src 'self'",
            "base-uri 'self'",
            $cspFrameAncestors,
            "img-src 'self' data:",
            "font-src 'self'",
            "object-src 'none'",
            "connect-src 'self'",
            "script-src 'self' 'nonce-{$nonce}'",
            "style-src 'self' 'nonce-{$nonce}'",
            "frame-src 'self'",
            "form-action 'self'",
        ]);
        $response->headers->set(
            'Content-Security-Policy',
            $csp
        );

        // Restrict browser features
        $response->headers->set('Permissions-Policy', "geolocation=(), microphone=(), camera=(), payment=(), usb=(), bluetooth=()");

        // Force HTTPS in production
        if (config('app.env') === 'production') {
            $response->headers->set('Strict-Transport-Security', 'max-age=31536000; includeSubDomains');
        }

        return $response;
    }
}
